---
  - name: Start Treeserve
    hosts: localhost
    connection: local
    tasks:
      - name: Install dependencies (pip)
        pip:
          name:
            - botocore
            - boto3
            - docker
            - PyYAML
            - docker-compose

      - name: Clone Branchserve repo
        git:
          repo: 'https://github.com/wtsi-hgi/branchserve.git'
          dest: /home/ubuntu/branchserve

      - name: Get mpistat chunk from S3
        aws_s3:
          aws_access_key: "{{ lookup('env', 'S3_AWS_ACCESS_KEY') }}"
          aws_secret_key: "{{ lookup('env', 'S3_AWS_SECRET_KEY') }}"
          bucket: branchserve
          dest: /home/ubuntu/branchserve/input.gz
          mode: get
          object: "mpistat/{{ lookup('env', 'S3_GROUP_NAME') }}.dat.gz"
          s3_url: "{{ lookup('env', 'S3_SANGER_URL') }}"
          rgw: yes

      - name: Get groupfile from S3
        aws_s3:
          aws_access_key: "{{ lookup('env', 'S3_AWS_ACCESS_KEY') }}"
          aws_secret_key: "{{ lookup('env', 'S3_AWS_SECRET_KEY') }}"
          bucket: branchserve
          dest: /etc/group
          mode: get
          object: "mpistat/groupfile"
          s3_url: "{{ lookup('env', 'S3_SANGER_URL') }}"
          rgw: yes

      - name: Get passwdfile from S3
        aws_s3:
          aws_access_key: "{{ lookup('env', 'S3_AWS_ACCESS_KEY') }}"
          aws_secret_key: "{{ lookup('env', 'S3_AWS_SECRET_KEY') }}"
          bucket: branchserve
          dest: /etc/passwd
          mode: get
          object: "mpistat/passwdfile"
          s3_url: "{{ lookup('env', 'S3_SANGER_URL') }}"
          rgw: yes

      - name: Launch Treeserve docker container
        docker_compose:
          project_src: /home/ubuntu/branchserve
